### PR TITLE
Archive access point

### LINKED ISSUE #1: Add field in models for access point of archived URL
@vphill requested a field in the Project? model (or a set of fields) that would allow us to put the base URL for an OpenWayback instance that provides access to the seeds crawled in the Nomination Tool. 
If that seed is present then we could have a link directly into the archive created for it. 
Might make the nomination tool an access system as well. 
(issue moved over from Trac)

### PR DESCRIPTION
**Pull request by somexpert**
This purpose of this PR is to add an access point to archived URLs from within the app. fixes #1

### CODE REVIEW

**Comment by ldko** [comment]
In this PR we could include a change to url_listing.html where if the project's archive_url has been given a value, we display under the "URL" (url entity) an "Archived URL" heading and a link to what should allow access to the url in the archive.

**Comment by somexpert** [comment]
@ldko, @vphill, @jason-ellis, @jthomale, this is ready for review

**Comment by ldko** [comment]
We should probably support both base urls entered with the slash on the end or not.

**Comment by somexpert** [comment]
will do

**Comment by ldko** [comment]
I think we could do something with the logic of:
```
    def clean(self):
        if self.archive_url and not self.archive_url.endswith('/'):
            self.archive_url = '{}{}'.format(self.archive_url, '/')
```
Also, I think we need `blank=True` for the `archive_url` field assignment in the model either way.

**Comment by somexpert** [comment]
Ok, I'll add that in there and test it out. And do we need the `blank=True` since we have the `null=True`?

**Comment by ldko** [comment]
I believe we need the blank=True in order to make it not a required input in forms (including the admin).

**Comment by somexpert** [comment]
alright, I'll add that in there too

**Comment by ldko** [comment]
:+1:

**Comment by jason-ellis** [comment]
:+1:

**Pull request merged**
